[build]
  command = "npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  API_BASE_URL = "https://growing-together-app.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
